<!DOCTYPE html>
<html lang="en">
<head>
	<base href="<?= URL ?>" />
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
	<meta name="author" content="Coderthemes">
	<link rel="shortcut icon" href="views/favicon.ico">
	<title><?= APP ?></title>
	<!-- DataTables -->
	<link href="views/backend/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
	<link href="views/backend/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
	<!-- Responsive datatable examples -->
	<link href="views/backend/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
	<link href="views/backend/plugins/tablesaw/dist/tablesaw.css" rel="stylesheet" type="text/css" />
	<!-- Moodals -->
	<link href="views/backend/plugins/custombox/dist/custombox.min.css" rel="stylesheet">
	<link href="views/backend/plugins/switchery/switchery.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="views/backend/plugins/morris/morris.css">
	<!-- Plugins Bootstrap -->
	<link href="views/backend/plugins/switchery/switchery.min.css" rel="stylesheet" />
	<link href="views/backend/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="views/backend/assets/css/icons.css" rel="stylesheet" type="text/css">
	<link href="views/backend/assets/css/style.css" rel="stylesheet" type="text/css">
	<script src="views/backend/assets/js/modernizr.min.js"></script>
</head>
