		<?php $var_m_dvdesign = new dvdesignModel; ?>
		<?php $df_sql_select_session = $var_m_dvdesign->sql_select_session(); ?>
		<div class="topbar">
			<div class="topbar-left">
				<div class="text-center">
					<a href="home/" class="logo">
						<i class="mdi mdi-radar"></i>
					</a>
				</div>
			</div>
			<nav class="navbar-custom">
				<ul class="list-inline float-right mb-0">
					<!--<li class="list-inline-item dropdown notification-list">
						<a class="nav-link dropdown-toggle arrow-none waves-light waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
							<i class="mdi mdi-bell noti-icon"></i>
							<span class="badge badge-pink noti-icon-badge">4</span>
						</a>
						<div class="dropdown-menu dropdown-menu-right dropdown-arrow dropdown-menu-lg" aria-labelledby="Preview">
							<div class="dropdown-item noti-title">
								<h5 class="font-16">
									<span class="badge badge-danger float-right">5</span>
									<span>Notification</span>
								</h5>
							</div>
							<a href="javascript:void(0);" class="dropdown-item notify-item">
								<div class="notify-icon bg-success">
									<i class="mdi mdi-comment-account"></i>
								</div>
								<p class="notify-details">
									Robert S. Taylor commented on Admin <small class="text-muted">1 min ago</small>
								</p>
							</a>
							<a href="javascript:void(0);" class="dropdown-item notify-item">
								<div class="notify-icon bg-info">
									<i class="mdi mdi-account"></i>
								</div>
								<p class="notify-details">
									New user registered. <small class="text-muted">1 min ago</small>
								</p>
							</a>
							<a href="javascript:void(0);" class="dropdown-item notify-item">
								<div class="notify-icon bg-danger">
									<i class="mdi mdi-airplane"></i>
								</div>
								<p class="notify-details">
									Carlos Crouch liked <b>Admin</b> <small class="text-muted">1 min ago</small>
								</p>
							</a>
							<a href="javascript:void(0);" class="dropdown-item notify-item notify-all">
								View All
							</a>
						</div>
					</li>-->
					<li class="list-inline-item dropdown notification-list">
						<a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
							<em class="text-white mdi mdi-account"></em>
							<?php if (false != $df_sql_select_session): ?>
								<?php foreach ($df_sql_select_session as $key): ?>
									<span class="text-white"><?= $key[d_az_user_t_login] ?></span>
								<?php endforeach; ?>
							<?php endif; ?>
						</a>
						<div class="dropdown-menu dropdown-menu-right profile-dropdown " aria-labelledby="Preview">
							<!--<div class="dropdown-item noti-title">
								<h5 class="text-overflow">
									<small>Welcome ! admin</small>
								</h5>
							</div>-->
							<a href="dashboard/" class="dropdown-item notify-item">
								<em class="mdi mdi-view-dashboard"></em>
								<span>Dashboard</span>
							</a>
							<a href="profile/update/<?= $_SESSION[SESS_APP_ID] ?>/" class="dropdown-item notify-item">
								<em class="mdi mdi-account-card-details"></em>
								<span>Perfil</span>
							</a>
							<a href="record/" class="dropdown-item notify-item">
								<em class="mdi mdi-clipboard-text"></em>
								<span>Historial</span>
							</a>
							<a href="calendar/" class="dropdown-item notify-item">
								<em class="mdi mdi-calendar"></em>
								<span>Calendario</span>
							</a>
							<a href="settings/" class="dropdown-item notify-item">
								<em class="mdi mdi-settings"></em>
								<span>Ajustes</span>
							</a>
							<a href="help/" class="dropdown-item notify-item">
								<em class="mdi mdi-help"></em>
								<span>Ayuda</span>
							</a>
							<a href="logout/" class="dropdown-item notify-item">
								<em class="mdi mdi-logout"></em>
								<span>Cerrar Sesion</span>
							</a>
						</div>
					</li>
				</ul>
				<ul class="list-inline menu-left mb-0">
					<li class="float-left">
						<button class="button-menu-mobile open-left waves-light waves-effect">
							<i class="mdi mdi-menu"></i>
						</button>
					</li>
					<!--<li class="hide-phone app-search">
						<form role="search" class="">
							<input type="text" placeholder="Search..." class="form-control">
							<a href="">
								<i class="fa fa-search"></i>
							</a>
						</form>
					</li>-->
				</ul>
			</nav>
		</div>
		