INSERT INTO `bd_pd_compensar`.`car01_datosdeudorcastigo` ()
SELECT  FROM `bd_pd_test`.`car01_datosdeudorcastigo`;

INSERT INTO `bd_pd_compensar`.`car01_datosdeudorcastigo_calls_c` (`id`, `date_modified`, `deleted`, `car01_datosdeudorcastigo_callscar01_datosdeudorcastigo_ida`, `car01_datosdeudorcastigo_callscalls_idb`)
SELECT `id`, `date_modified`, `deleted`, `car01_datosdeudorcastigo_callscar01_datosdeudorcastigo_ida`, `car01_datosdeudorcastigo_callscalls_idb` FROM `bd_pd_test`.`car01_datosdeudorcastigo_calls_c`;

INSERT INTO `bd_pd_compensar`.`car01_datosdeudorcastigo` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `numcre`, `docide`, `dircasatrabajador`, `direccion2`, `telcasatrabajador`, `telceltrabajador`, `telefono3`, `telefono4`, `tipidecod1`, `docidecod1`, `nomcod1`, `dircasacod1`, `telcasacod1`, `telcelcod1`, `tipidecod2`, `docidecod2`, `nomcod2`, `dircasacod2`, `telcasacod2`, `telcelcod2`, `diasmora`, `vlrcastcap`, `currency_id`, `valordeuda`, `negociacion1`, `negociacion2`, `negociacion3`, `asesor`, `barrido`, `ulttipificacion`, `fechaulttipificacion`, `correo`, `correo2`, `telefono2`, `nom_ref_fam1`, `dir_ref_fam1`, `tel_ref_fam1`, `cel_ref_fam1`, `nom_ref_fam2`, `dir_ref_fam2`, `tel_ref_fam2`, `cel_ref_fam2`, `nom_ref_fam3`, `dir_ref_fam3`, `tel_ref_fam3`, `cel_ref_fam3`, `nom_ref_per1`, `dir_ref_per1`, `tel_ref_per1`, `cel_ref_per1`, `nom_ref_per2`, `dir_ref_per2`, `tel_ref_per2`, `cel_ref_per2`, `nom_ref_com1`, `dir_ref_com1`, `tel_ref_com1`, `cel_ref_com1`, `nom_ref_com2`, `dir_ref_com2`, `tel_ref_com2`, `cel_ref_com2`, `campaign`, `tipocartera`, `proyeccion`, `fechaproyeccion`, `email`, `mora_desembolso`, `fecha_ult_abono`, `nit_empresa`, `nombre_empresa`, `nombre_dependencia`, `mail_cod`, `nombre_linea`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `numcre`, `docide`, `dircasatrabajador`, `direccion2`, `telcasatrabajador`, `telceltrabajador`, `telefono3`, `telefono4`, `tipidecod1`, `docidecod1`, `nomcod1`, `dircasacod1`, `telcasacod1`, `telcelcod1`, `tipidecod2`, `docidecod2`, `nomcod2`, `dircasacod2`, `telcasacod2`, `telcelcod2`, `diasmora`, `vlrcastcap`, `currency_id`, `valordeuda`, `negociacion1`, `negociacion2`, `negociacion3`, `asesor`, `barrido`, `ulttipificacion`, `fechaulttipificacion`, `correo`, `correo2`, `telefono2`, `nom_ref_fam1`, `dir_ref_fam1`, `tel_ref_fam1`, `cel_ref_fam1`, `nom_ref_fam2`, `dir_ref_fam2`, `tel_ref_fam2`, `cel_ref_fam2`, `nom_ref_fam3`, `dir_ref_fam3`, `tel_ref_fam3`, `cel_ref_fam3`, `nom_ref_per1`, `dir_ref_per1`, `tel_ref_per1`, `cel_ref_per1`, `nom_ref_per2`, `dir_ref_per2`, `tel_ref_per2`, `cel_ref_per2`, `nom_ref_com1`, `dir_ref_com1`, `tel_ref_com1`, `cel_ref_com1`, `nom_ref_com2`, `dir_ref_com2`, `tel_ref_com2`, `cel_ref_com2`, `campaign`, `tipocartera`, `proyeccion`, `fechaproyeccion`, `email`, `mora_desembolso`, `fecha_ult_abono`, `nit_empresa`, `nombre_empresa`, `nombre_dependencia`, `mail_cod`, `nombre_linea` FROM `bd_pd_test`.`car01_datosdeudorcastigo`;


INSERT INTO `bd_pd_compensar`.`calls` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `duration_hours`, `duration_minutes`, `date_start`, `date_end`, `parent_type`, `status`, `direction`, `parent_id`, `reminder_time`, `email_reminder_time`, `email_reminder_sent`, `outlook_id`, `repeat_type`, `repeat_interval`, `repeat_dow`, `repeat_until`, `repeat_count`, `repeat_parent_id`, `recurring_source`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `duration_hours`, `duration_minutes`, `date_start`, `date_end`, `parent_type`, `status`, `direction`, `parent_id`, `reminder_time`, `email_reminder_time`, `email_reminder_sent`, `outlook_id`, `repeat_type`, `repeat_interval`, `repeat_dow`, `repeat_until`, `repeat_count`, `repeat_parent_id`, `recurring_source` FROM `bd_pd_test`.`calls`;

INSERT INTO `bd_pd_compensar`.`calls_users` (`id`, `call_id`, `user_id`, `required`, `accept_status`, `date_modified`, `deleted`)
SELECT `id`, `call_id`, `user_id`, `required`, `accept_status`, `date_modified`, `deleted` FROM `bd_pd_test`.`calls_users`;