INSERT INTO `bd_pd_coasmedas`.`coa01_datosdeudor` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `identificacion`, `currency_id`, `direccion1`, `direccion2`, `telefono1`, `telefono2`, `telefono3`, `telefono4`, `ciudad`, `profesion`, `nro_obligacion`, `dias_mora`, `codigo_oficina`, `nombre_oficina`, `fech_des`, `int_vencido`, `mora_causada`, `seguro_vencido`, `otros_conceptos`, `valor_vencido`, `saldo_capital`, `nom_cod1`, `dir_cod`, `ciudad_cod`, `tel1_cod`, `tel2_cod`, `cedula_cod`, `fech_aportes`, `aportes_vencidos`, `linea`, `cta_vencida1`, `cta_vencida2`, `cta_vencida3`, `correo`, `correo_cod`, `nom_ref_fam1`, `dir_ref_fam1`, `tel_ref_fam1`, `cel_ref_fam1`, `nom_ref_fam2`, `dir_ref_fam2`, `tel_ref_fam2`, `cel_ref_fam2`, `nom_ref_fam3`, `dir_ref_fam3`, `tel_ref_fam3`, `cel_ref_fam3`, `nom_ref_per1`, `dir_ref_per1`, `tel_ref_per1`, `cel_ref_per1`, `nom_ref_per2`, `dir_ref_per2`, `tel_ref_per2`, `cel_ref_per2`, `nom_ref_com1`, `dir_ref_com1`, `tel_ref_com1`, `cel_ref_com1`, `nom_ref_com2`, `dir_ref_com2`, `tel_ref_com2`, `cel_ref_com2`, `asesor`, `fechaultimatip`, `barrido`, `ulttipificacion`, `campaign`, `proyeccion`, `fech_ult_pago`, `valor_ult_pago`, `capital_vencido`, `fechaproyeccion`, `pago`, `fechapago`, `seguimiento`, `fecha_corte`, `aportes`, `gestion_especial`, `nivel_riesgo`, `valoracuerdo`, `interes_corriente`, `interes_mora_no_causado`, `valor_total`, `estado_cobranza`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `identificacion`, `currency_id`, `direccion1`, `direccion2`, `telefono1`, `telefono2`, `telefono3`, `telefono4`, `ciudad`, `profesion`, `nro_obligacion`, `dias_mora`, `codigo_oficina`, `nombre_oficina`, `fech_des`, `int_vencido`, `mora_causada`, `seguro_vencido`, `otros_conceptos`, `valor_vencido`, `saldo_capital`, `nom_cod1`, `dir_cod`, `ciudad_cod`, `tel1_cod`, `tel2_cod`, `cedula_cod`, `fech_aportes`, `aportes_vencidos`, `linea`, `cta_vencida1`, `cta_vencida2`, `cta_vencida3`, `correo`, `correo_cod`, `nom_ref_fam1`, `dir_ref_fam1`, `tel_ref_fam1`, `cel_ref_fam1`, `nom_ref_fam2`, `dir_ref_fam2`, `tel_ref_fam2`, `cel_ref_fam2`, `nom_ref_fam3`, `dir_ref_fam3`, `tel_ref_fam3`, `cel_ref_fam3`, `nom_ref_per1`, `dir_ref_per1`, `tel_ref_per1`, `cel_ref_per1`, `nom_ref_per2`, `dir_ref_per2`, `tel_ref_per2`, `cel_ref_per2`, `nom_ref_com1`, `dir_ref_com1`, `tel_ref_com1`, `cel_ref_com1`, `nom_ref_com2`, `dir_ref_com2`, `tel_ref_com2`, `cel_ref_com2`, `asesor`, `fechaultimatip`, `barrido`, `ulttipificacion`, `campaign`, `proyeccion`, `fech_ult_pago`, `valor_ult_pago`, `capital_vencido`, `fechaproyeccion`, `pago`, `fechapago`, `seguimiento`, `fecha_corte`, `aportes`, `gestion_especial`, `nivel_riesgo`, `valoracuerdo`, `interes_corriente`, `interes_mora_no_causado`, `valor_total`, `estado_cobranza` FROM `bd_pd_test`.`coa01_datosdeudor`;

INSERT INTO `bd_pd_coasmedas`.`coa01_obligacionesdeudor` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `identificacion`, `nro_obligacion`, `dias_mora`, `codigo_oficina`, `nombre_oficina`, `valor_ult_pago`, `currency_id`, `capital_vencido`, `int_vencido`, `mora_causada`, `seguro_vencido`, `otros_conceptos`, `valor_vencido`, `saldo_capital`, `linea`, `cta_vencida1`, `cta_vencida2`, `cta_vencida3`, `asesor`, `ulttipificacion`, `aportes_vencidos`, `fech_aportes`, `fech_ult_pago`, `fech_des`, `rango_mora`, `nivel_riesgo`, `campaign`, `aportes`, `interes_corriente`, `interes_mora_no_causado`, `valor_total`, `estado_cobranza`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `identificacion`, `nro_obligacion`, `dias_mora`, `codigo_oficina`, `nombre_oficina`, `valor_ult_pago`, `currency_id`, `capital_vencido`, `int_vencido`, `mora_causada`, `seguro_vencido`, `otros_conceptos`, `valor_vencido`, `saldo_capital`, `linea`, `cta_vencida1`, `cta_vencida2`, `cta_vencida3`, `asesor`, `ulttipificacion`, `aportes_vencidos`, `fech_aportes`, `fech_ult_pago`, `fech_des`, `rango_mora`, `nivel_riesgo`, `campaign`, `aportes`, `interes_corriente`, `interes_mora_no_causado`, `valor_total`, `estado_cobranza` FROM `bd_pd_test`.`coa01_obligacionesdeudor`;

INSERT INTO `bd_pd_coasmedas`.`coa01_datosdeudor_audit` (`id`, `parent_id`, `date_created`, `created_by`, `field_name`, `data_type`, `before_value_string`, `after_value_string`, `before_value_text`, `after_value_text`)
SELECT `id`, `parent_id`, `date_created`, `created_by`, `field_name`, `data_type`, `before_value_string`, `after_value_string`, `before_value_text`, `after_value_text` FROM `bd_pd_test_two`.`coa01_datosdeudor_audit`;

INSERT INTO `bd_pd_coasmedas`.`coa01_obligacionesdeudor_audit` (`id`, `parent_id`, `date_created`, `created_by`, `field_name`, `data_type`, `before_value_string`, `after_value_string`, `before_value_text`, `after_value_text`)
SELECT `id`, `parent_id`, `date_created`, `created_by`, `field_name`, `data_type`, `before_value_string`, `after_value_string`, `before_value_text`, `after_value_text` FROM `bd_pd_test_two`.`coa01_obligacionesdeudor_audit`;

INSERT INTO `bd_pd_coasmedas`.`calls` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `duration_hours`, `duration_minutes`, `date_start`, `date_end`, `parent_type`, `status`, `direction`, `parent_id`, `reminder_time`, `email_reminder_time`, `email_reminder_sent`, `outlook_id`, `repeat_type`, `repeat_interval`, `repeat_dow`, `repeat_until`, `repeat_count`, `repeat_parent_id`, `recurring_source`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `duration_hours`, `duration_minutes`, `date_start`, `date_end`, `parent_type`, `status`, `direction`, `parent_id`, `reminder_time`, `email_reminder_time`, `email_reminder_sent`, `outlook_id`, `repeat_type`, `repeat_interval`, `repeat_dow`, `repeat_until`, `repeat_count`, `repeat_parent_id`, `recurring_source` FROM `bd_pd_test_two`.`calls`;

INSERT INTO `bd_pd_coasmedas`.`calls_users` (`id`, `call_id`, `user_id`, `required`, `accept_status`, `date_modified`, `deleted`)
SELECT `id`, `call_id`, `user_id`, `required`, `accept_status`, `date_modified`, `deleted` FROM `bd_pd_test_two`.`calls_users`;

