-- Codigo para copiar de una tabla a otra en base de datos de datos deudor
INSERT INTO `bd_pd_helm_bank_v`.`he01_datosdeudor` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `codigocliente`, `tipoid`, `numeroid`, `codigoejecutivo`, `ejecutivo`, `codigooficina`, `oficina`, `tipocartera`, `casaexterna`, `asesorcadri`, `direccion`, `direccion2`, `ciudadcontacto`, `telefono`, `telefono2`, `telefono3`, `celular`, `correo`, `correo2`, `codeudor`, `telcodeudor`, `telcodeudor2`, `ciudadtelcodeudor`, `ciudadtelcodeudor2`, `telcontacto`, `observaciones`, `currency_id`, `asesor`, `campaign`, `barrido`, `ulttipificacion`, `pago`, `proyeccion`, `seguimiento`, `endeudamientocastigo`, `nom_ref_fam1`, `dir_ref_fam1`, `tel_ref_fam1`, `cel_ref_fam1`, `nom_ref_fam2`, `dir_ref_fam2`, `tel_ref_fam2`, `cel_ref_fam2`, `nom_ref_fam3`, `dir_ref_fam3`, `tel_ref_fam3`, `cel_ref_fam3`, `nom_ref_per1`, `dir_ref_per1`, `tel_ref_per1`, `cel_ref_per1`, `nom_ref_per2`, `dir_ref_per2`, `tel_ref_per2`, `cel_ref_per2`, `nom_ref_com1`, `dir_ref_com1`, `tel_ref_com1`, `cel_ref_com1`, `nom_ref_com2`, `dir_ref_com2`, `tel_ref_com2`, `cel_ref_com2`, `gestion_banco`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `codigocliente`, `tipoid`, `numeroid`, `codigoejecutivo`, `ejecutivo`, `codigooficina`, `oficina`, `tipocartera`, `casaexterna`, `asesorcadri`, `direccion`, `direccion2`, `ciudadcontacto`, `telefono`, `telefono2`, `telefono3`, `celular`, `correo`, `correo2`, `codeudor`, `telcodeudor`, `telcodeudor2`, `ciudadtelcodeudor`, `ciudadtelcodeudor2`, `telcontacto`, `observaciones`, `currency_id`, `asesor`, `campaign`, `barrido`, `ulttipificacion`, `pago`, `proyeccion`, `seguimiento`, `endeudamientocastigo`, `nom_ref_fam1`, `dir_ref_fam1`, `tel_ref_fam1`, `cel_ref_fam1`, `nom_ref_fam2`, `dir_ref_fam2`, `tel_ref_fam2`, `cel_ref_fam2`, `nom_ref_fam3`, `dir_ref_fam3`, `tel_ref_fam3`, `cel_ref_fam3`, `nom_ref_per1`, `dir_ref_per1`, `tel_ref_per1`, `cel_ref_per1`, `nom_ref_per2`, `dir_ref_per2`, `tel_ref_per2`, `cel_ref_per2`, `nom_ref_com1`, `dir_ref_com1`, `tel_ref_com1`, `cel_ref_com1`, `nom_ref_com2`, `dir_ref_com2`, `tel_ref_com2`, `cel_ref_com2`, `gestion_banco` FROM `BDhelm_2`.`he01_datosdeudor_vigente`;




-- Codigo para copiar de una tabla a otra en base de datos de productos deudor
-- Falta copiar los campos siguientes: fechaproyeccion, fechapago

INSERT INTO `bd_pd_helm_bank_v`.`he01_productosdeudor` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `codigocliente`, `numeroid`, `tipocartera`, `codigooficina`, `oficina`, `codigoproducto`, `numeroproducto`, `nombreproducto`, `banca`, `fechavinculacion`, `estrategiavinculacion`, `fechadesembolso`, `calificacionactual`, `provisionactual`, `currency_id`, `endeudamientocastigo`, `fechacastigo`, `diasmora`, `rangomora`, `capitalinicial`, `saldototal`, `saldocapital`, `saldomora`, `saldointcorriente`, `saldointmora`, `saldootroscargos`, `saldoextracont`, `pagominimo`, `pagominimocap`, `pagominimointcte`, `pagominimointmora`, `pagominimootros`, `pagominimoextra`, `rangomorainicial`, `campaign`, `ulttipificacion`, `proyeccion`, `pago`, `fechacorte`, `gestion_banco`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `codigocliente`, `numeroid`, `tipocartera`, `codigooficina`, `oficina`, `codigoproducto`, `numeroproducto`, `nombreproducto`, `banca`, `fechavinculacion`, `estrategiavinculacion`, `fechadesembolso`, `calificacionactual`, `provisionactual`, `currency_id`, `endeudamientocastigo`, `fechacastigo`, `diasmora`, `rangomora`, `capitalinicial`, `saldototal`, `saldocapital`, `saldomora`, `saldointcorriente`, `saldointmora`, `saldootroscargos`, `saldoextracont`, `pagominimo`, `pagominimocap`, `pagominimointcte`, `pagominimointmora`, `pagominimootros`, `pagominimoextra`, `rangomorainicial`, `campaign`, `ulttipificacion`, `proyeccion`, `pago`, `fechacorte`, `gestion_banco` FROM `BDhelm_2`.`he01_productosdeudor_vigente`;



TRUNCATE TABLE `bd_pd_helm_bank_v`.`he01_base_consolidada`;

-- Codigo para copiar de una tabla a otra en base de datos de datos deudor
INSERT INTO `bd_pd_helm_bank_v`.`he01_base_consolidada` (`id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `cedula`, `numero_de_producto`, `nombre_del_producto`, `cap_inicial`, `currency_id`)
SELECT `id`, `name`, `date_entered`, `date_modified`, `modified_user_id`, `created_by`, `description`, `deleted`, `assigned_user_id`, `numeroid`, `numeroproducto`, `nombreproducto`, `saldocapital`, `currency_id` FROM `BDhelm_2`.`he01_productosdeudor_vigente`;



UPDATE `BD_Coasmedas_2016`.`coa01_obligacionesdeudor` a1 SET a1.`dias_mora` = (SELECT p.`dias_mora` FROM `BD_Coasmedas_2016`.`coa01_datosdeudor_montaje_actualizacion` p WHERE p.`nro_obligacion` = a1.`nro_obligacion` AND p.`identificacion` = a1.`identificacion` LIMIT 0 , 1) WHERE a1.`deleted` = 0;