<?= $this->insert('backend/design/header'); ?>
<body class="fixed-left">
	<div id="wrapper">
		<?= $this->insert('backend/design/topbar'); ?>
		<?= $this->insert('backend/design/sidebar-start'); ?>
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<?= $this->insert('backend/design/content-menu'); ?>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="card-box table-responsive">
								<div class="form-group">
									<?php if (false != $df_sql_permits_t_value_read_all): ?>
										<a href="<?= $df_var_controller; ?>read/" class="btn btn-sm btn-outline-dark">
											<em class="mdi mdi-arrow-left-bold-hexagon-outline"></em>
											<span>Listar Resultados</span>
										</a>
									<?php endif ?>
								</div>
								<table id="datatable-buttons" class="table table-sm table-condensed table-striped table-bordered">
									<thead>
										<tr>
											<th>#</th>
											<th>Fecha Cambio</th>
											<th>Nombre</th>
											<th>Valor</th>
										</tr>
									</thead>
									<tbody>
										<?php if (false != $df_sql_controller_change): ?>
											<?php foreach ($df_sql_controller_change as $key): ?>
												<tr>
													<td>#</td>
													<td><?= $key[d_az_change_deleted_m_date_modified]; ?></td>
													<td><?= $key[d_az_change_deleted_t_name]; ?></td>
													<td><?= $key[d_az_change_deleted_t_value]; ?></td>
												</tr>
											<?php endforeach; ?>
										<?php endif; ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?= $this->insert('backend/design/footer'); ?>
		</div>
	</div>
	<?= $this->insert('backend/design/script'); ?>
</body>
</html>