<?= $this->insert('backend/design/header'); ?>
<body class="fixed-left">
	<div id="wrapper">
		<?= $this->insert('backend/design/topbar'); ?>
		<?= $this->insert('backend/design/sidebar-start'); ?>
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<?= $this->insert('backend/design/content-menu'); ?>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="card-box table-responsive">
								<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_update_pd_data_personal">
									<div class="row">
										<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
											<div class="form-group">
												<a href="<?= $df_var_controller; ?>read/" class="btn btn-sm btn-outline-dark">
													<em class="mdi mdi-arrow-left-bold-hexagon-outline"></em>
													<span>Listar Resultados</span>
												</a>
												<button type="button" class="btn btn-sm btn-outline-success" id="form_btn_update_pd_data_personal">
													<em class="mdi mdi-rotate-3d"></em>
													<span>Actualizar Registro</span>
												</button>
											</div>
											<div class="hide" id="form_ajax_pd_data_personal"></div>
										</div>
										<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
											<div class="form-group bg-white">
												<div class="modal-content">
													<div class="modal-header bg-white">
														<label>
															<span>Datos Personales</span>
														</label>
													</div>
													<div class="modal-body">
														<div class="row">
															<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
																<div class="form-group">
																	<label>
																		<span>Id:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_id" class="form-control" placeholder="Digita el texto ..." required="" readonly="" value="<?= $_GET['field_id']; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Nombres:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_names" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_names]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Apellidos:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_surnames" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_surnames]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Tipo Documento:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_document_type" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_document_type): ?>
																				<?php foreach ($df_sql_select_tc_pd_document_type as $key): ?>
																					<?php if ($key[d_pd_document_type_id_pd_document_type] == $df_sql_controller_update[d_pd_data_personal_v_id_pd_document_type]): ?>
																						<option value="<?= $key[d_pd_document_type_id_pd_document_type]; ?>" selected>
																							<?= $key[d_pd_document_type_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_document_type_id_pd_document_type]; ?>">
																							<?= $key[d_pd_document_type_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Identificacion:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_identification" class="form-control" placeholder="Digita el texto ..." required="" disabled="" readonly="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_identification]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Telefono Fijo:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_phone_fixed" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_phone_fixed]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Telefono Movil:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_phone_movil" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_phone_movil]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Correo Electronico:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_email" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_email]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Direccion:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_address" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_address]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Fecha Nacimiento:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="date" name="field_birth_date" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_update[d_pd_data_personal_t_birth_date]; ?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Lugar Nacimiento:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_birth_place" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_birth_place): ?>
																				<?php foreach ($df_sql_select_tc_pd_birth_place as $key): ?>
																					<?php if ($key[d_pd_birth_place_id_pd_birth_place] == $df_sql_controller_update[d_pd_data_personal_v_id_pd_birth_place]): ?>
																						<option value="<?= $key[d_pd_birth_place_id_pd_birth_place]; ?>" selected>
																							<?= $key[d_pd_birth_place_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_birth_place_id_pd_birth_place]; ?>">
																							<?= $key[d_pd_birth_place_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Estado Civil:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_civil_status" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_civil_status): ?>
																				<?php foreach ($df_sql_select_tc_pd_civil_status as $key): ?>
																					<?php if ($key[d_pd_civil_status_id_pd_civil_status] == $df_sql_controller_update[d_pd_data_personal_v_id_pd_civil_status]): ?>
																						<option value="<?= $key[d_pd_civil_status_id_pd_civil_status]; ?>" selected>
																							<?= $key[d_pd_civil_status_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_civil_status_id_pd_civil_status]; ?>">
																							<?= $key[d_pd_civil_status_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Eps:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_eps" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_eps): ?>
																				<?php foreach ($df_sql_select_tc_pd_eps as $key): ?>
																					<?php if ($key[d_pd_eps_id_pd_eps] == $df_sql_controller_update[d_pd_data_personal_v_id_pd_eps]): ?>
																						<option value="<?= $key[d_pd_eps_id_pd_eps]; ?>" selected>
																							<?= $key[d_pd_eps_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_eps_id_pd_eps]; ?>">
																							<?= $key[d_pd_eps_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Nivel Estudio:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_level_study" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_level_study): ?>
																				<?php foreach ($df_sql_select_tc_pd_level_study as $key): ?>
																					<?php if ($key[d_pd_level_study_id_pd_level_study] == $df_sql_controller_update[d_pd_data_personal_v_id_pd_level_study]): ?>
																						<option value="<?= $key[d_pd_level_study_id_pd_level_study]; ?>" selected>
																							<?= $key[d_pd_level_study_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_level_study_id_pd_level_study]; ?>">
																							<?= $key[d_pd_level_study_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Barrio:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_neighborhood" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_neighborhood): ?>
																				<?php foreach ($df_sql_select_tc_pd_neighborhood as $key): ?>
																					<?php if ($key[d_pd_neighborhood_id_pd_neighborhood] == $df_sql_controller_update[d_pd_data_personal_v_id_pd_neighborhood]): ?>
																						<option value="<?= $key[d_pd_neighborhood_id_pd_neighborhood]; ?>" selected>
																							<?= $key[d_pd_neighborhood_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_neighborhood_id_pd_neighborhood]; ?>">
																							<?= $key[d_pd_neighborhood_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Pension:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_pension" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_pension): ?>
																				<?php foreach ($df_sql_select_tc_pd_pension as $key): ?>
																					<?php if ($key[d_pd_pension_id_pd_pension] == $df_sql_controller_update[d_pd_data_personal_v_id_pd_pension]): ?>
																						<option value="<?= $key[d_pd_pension_id_pd_pension]; ?>" selected>
																							<?= $key[d_pd_pension_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_pension_id_pd_pension]; ?>">
																							<?= $key[d_pd_pension_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3">
																<div class="form-group">
																	<label>
																		<span>Estado:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_state" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_controller_read_state): ?>
																				<?php foreach ($df_sql_controller_read_state as $key): ?>
																					<?php if ($key['lbl_az_state_t_value'] == $df_sql_controller_update[d_pd_data_personal_m_status]): ?>
																						<option value="<?= $key['lbl_az_state_t_value']; ?>" selected>
																							<?= $key['lbl_az_state_t_name']; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key['lbl_az_state_t_value']; ?>">
																							<?= $key['lbl_az_state_t_name']; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
											<div class="form-group bg-white">
												<div class="modal-content">
													<div class="modal-header bg-white">
														<label>
															<span>Datos Empresariales</span>
														</label>
													</div>
													<div class="modal-body">
														<div class="row">
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Rediferido:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_data_personal" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if ($df_sql_controller_inner[d_pd_data_business_t_data_personal] == 'Ninguno'): ?>
																				<option value="Ninguno" selected>Ninguno</option>
																			<?php else: ?>
																				<option value="Ninguno">Ninguno</option>
																			<?php endif ?>
																			<?php if (false != $df_sql_select_tc_pd_data_personal): ?>
																				<?php foreach ($df_sql_select_tc_pd_data_personal as $key): ?>
																					<?php if ($key[d_pd_data_personal_id_pd_data_personal] == $df_sql_controller_inner[d_pd_data_business_t_data_personal]): ?>
																						<option value="<?= $key[d_pd_data_personal_id_pd_data_personal]; ?>" selected>
																							<?= $key[d_pd_data_personal_t_names] . ' ' . $key[d_pd_data_personal_t_surnames]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_data_personal_id_pd_data_personal]; ?>">
																							<?= $key[d_pd_data_personal_t_names] . ' ' . $key[d_pd_data_personal_t_surnames]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Fecha Ingreso:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="date" name="field_date_admission" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_inner[d_pd_data_business_t_date_admission]?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Fecha Terminacion Contrato:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="date" name="field_date_contract_termination" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_inner[d_pd_data_business_t_date_contract_termination]?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Valor Bono:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_value_bonus" class="form-control" placeholder="Digita el texto ..." required="" value="<?= $df_sql_controller_inner[d_pd_data_business_t_value_bonus]?>">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Campaña:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_campaign" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_campaign): ?>
																				<?php foreach ($df_sql_select_tc_pd_campaign as $key): ?>
																					<?php if ($key[d_pd_campaign_id_pd_campaign] == $df_sql_controller_inner[d_pd_data_business_v_id_pd_campaign]): ?>
																						<option value="<?= $key[d_pd_campaign_id_pd_campaign]; ?>" selected>
																							<?= $key[d_pd_campaign_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_campaign_id_pd_campaign]; ?>">
																							<?= $key[d_pd_campaign_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Tipo Contrato:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_contract_type" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_contract_type): ?>
																				<?php foreach ($df_sql_select_tc_pd_contract_type as $key): ?>
																					<?php if ($key[d_pd_contract_type_id_pd_contract_type] == $df_sql_controller_inner[d_pd_data_business_v_id_pd_contract_type]): ?>
																						<option value="<?= $key[d_pd_contract_type_id_pd_contract_type]; ?>" selected>
																							<?= $key[d_pd_contract_type_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_contract_type_id_pd_contract_type]; ?>">
																							<?= $key[d_pd_contract_type_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Cargo:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_employee_charge" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_employee_charge): ?>
																				<?php foreach ($df_sql_select_tc_pd_employee_charge as $key): ?>
																					<?php if ($key[d_pd_employee_charge_id_pd_employee_charge] == $df_sql_controller_inner[d_pd_data_business_v_id_pd_employee_charge]): ?>
																						<option value="<?= $key[d_pd_employee_charge_id_pd_employee_charge]; ?>" selected>
																							<?= $key[d_pd_employee_charge_t_name]; ?>
																						</option>
																					<?php else: ?>
																						<option value="<?= $key[d_pd_employee_charge_id_pd_employee_charge]; ?>">
																							<?= $key[d_pd_employee_charge_t_name]; ?>
																						</option>
																					<?php endif ?>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
																<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																	<div class="form-group">
																		<label>
																			<span>Salario Base:</span>
																		</label>
																		<div class="input-group input-group-sm">
																			<select name="field_base_salary" id="field_base_salary" class="form-control" required="">
																				<option value="0">Seleccionar</option>
																				<?php if (false != $df_sql_select_tc_pd_base_salary): ?>
																					<?php foreach ($df_sql_select_tc_pd_base_salary as $key): ?>
																						<?php if ($key[d_pd_base_salary_id_pd_base_salary] == $df_sql_controller_inner[d_pd_data_business_v_id_pd_base_salary]): ?>
																							<option value="<?= $key[d_pd_base_salary_id_pd_base_salary]; ?>" selected>
																								<?= $key[d_pd_base_salary_t_value]; ?>
																							</option>
																						<?php else: ?>
																							<option value="<?= $key[d_pd_base_salary_id_pd_base_salary]; ?>">
																								<?= $key[d_pd_base_salary_t_value]; ?>
																							</option>
																						<?php endif ?>
																					<?php endforeach; ?>
																				<?php else: ?>
																					<option value="0">No existen resultados</option>
																				<?php endif; ?>
																			</select>
																		</div>
																	</div>
																</div>
																<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																	<div class="form-group">
																		<label>
																			<span>Auxilio Transporte:</span>
																		</label>
																		<div class="input-group input-group-sm">
																			<select name="field_transport_assistance" id="field_transport_assistance" class="form-control" required="">
																				<option value="0">Seleccionar</option>
																				<?php if (false != $df_sql_select_tc_pd_transport_assistance): ?>
																					<?php foreach ($df_sql_select_tc_pd_transport_assistance as $key): ?>
																						<?php if ($key[d_pd_transport_assistance_id_pd_transport_assistance] == $df_sql_controller_inner[d_pd_data_business_v_id_pd_transport_assistance]): ?>
																							<option value="<?= $key[d_pd_transport_assistance_id_pd_transport_assistance]; ?>" selected>
																								<?= $key[d_pd_base_salary_t_value]; ?>
																							</option>
																						<?php else: ?>
																							<option value="<?= $key[d_pd_transport_assistance_id_pd_transport_assistance]; ?>">
																								<?= $key[d_pd_transport_assistance_t_value]; ?>
																							</option>
																						<?php endif ?>
																					<?php endforeach; ?>
																				<?php else: ?>
																					<option value="0">No existen resultados</option>
																				<?php endif; ?>
																			</select>
																		</div>
																	</div>
																</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<!--<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
											<div class="form-group">
												<label>
													<span>Descripcion:</span>
												</label>
												<div class="input-group input-group-sm">
													<textarea name="field_description" class="form-control" placeholder="Digita el texto ..." required="" rows="5"><?= $df_sql_controller_update[d_pd_data_personal_m_description]; ?></textarea>
												</div>
											</div>
										</div>-->
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?= $this->insert('backend/design/footer'); ?>
		</div>
	</div>
	<?= $this->insert('backend/design/script'); ?>
</body>
</html>