	<footer class="footer bg-dark text-white">
		<div class="container">
			<div class="row">
				<div class="colxs-12 col-sm-12 col-md-12 col-lg-12 text-center">
					<p class="copyright">
						Prisma Direct &copy; 2017 - <?= date('Y'); ?>
					</p>
				</div>
			</div>
			<!-- end row -->
		</div>
		<!-- end container -->
		<div class="container">
			<div class="row">
				<div class="colxs-12 col-sm-12 col-md-12 col-lg-12 text-center">
					<p class="copyright">
						Colaborador: Adison Jimenez &copy; 2017 - <?= date('Y'); ?>
					</p>
				</div>
			</div>
			<!-- end row -->
		</div>
		<!-- end container -->
	</footer>
	