<!DOCTYPE html>
<html lang="en">
<head>
	<base href="<?= URL ?>" />
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
	<meta name="author" content="Coderthemes">
	<link rel="shortcut icon" href="views/favicon.ico">
	<title><?= APP ?></title>
	<!-- DataTables -->
	<link href="views/backend/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
	<link href="views/backend/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />
	<!-- Responsive datatable examples -->
	<link href="views/backend/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
	<link href="views/backend/plugins/tablesaw/dist/tablesaw.css" rel="stylesheet" type="text/css" />
	
	<link href="views/backend/plugins/switchery/switchery.min.css" rel="stylesheet" />
	<link href='https://fonts.googleapis.com/css?family=Roboto:400,300,500' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
	<!-- Bootstrap core CSS -->
	<link href="views/frontend/css/bootstrap.min.css" rel="stylesheet">
	<!-- Animate -->
	<link href="views/frontend/css/animate.css" rel="stylesheet">
	<!-- Icon-font -->
	<link rel="stylesheet" type="text/css" href="views/frontend/css/themify-icons.css">
	<!-- Custom styles for this template -->
	<link href="views/frontend/css/style.css" rel="stylesheet">
	<script src="views/backend/assets/js/modernizr.min.js"></script>
</head>
