<div class="clearfix"></div>
	<!-- HOME -->
	<section class="home bg-img-1 parallax" data-stellar-background-ratio="0.5">
		<div class="bg-overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div class="home-wrapper text-center">
						<h1 class="animated fadeInDown wow" data-wow-delay=".1s">
							Prisma Direct - Advanced Solutions
						</h1>
						<p class="animated fadeInDown wow" data-wow-delay=".2s">
							Ofrece su experiencia y calidad, llevando con éxito cada proyecto. contamos con personal capacitado y calificado en todos los productos y servicios que comercializamos.
						</p>
						<!--<a href="" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow" data-wow-delay=".4s">
							Buy Now
						</a>-->
						<div class="clearfix"></div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- END HOME -->