	<div class="tagline">
		<div class="container">
			<div class="float-left">
				<div class="phone">
					<i class=" ti-mobile"></i>
					<span>+57 1 605 95 55</span>
				</div>
				<div class="email">
					<a href="mailto:#">
						<i class=" ti-email"></i>
						<span>support@prismadirect.net</span>
					</a>
				</div>
			</div>
			<div class="float-right">
				<ul class="top_socials">
					<li>
						<a href="javascript:void(0);">
							<i class=" ti-facebook"></i>
						</a>
					</li>
					<li>
						<a href="javascript:void(0);">
							<i class=" ti-skype"></i>
						</a>
					</li>
					<li>
						<a href="javascript:void(0);">
							<i class=" ti-twitter-alt"></i>
						</a>
					</li>
					<li>
						<a href="javascript:void(0);">
							<i class=" ti-github"></i>
						</a>
					</li>
				</ul>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	