<?= $this->insert('backend/design/header'); ?>
<body class="fixed-left">
	<div id="wrapper">
		<?= $this->insert('backend/design/topbar'); ?>
		<?= $this->insert('backend/design/sidebar-start'); ?>
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<?= $this->insert('backend/design/content-menu'); ?>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<?php if (false != $df_sql_tc_az_sub_menu_crud_order_by): ?>
								<div class="form-group">
									<?php foreach ($df_sql_tc_az_sub_menu_crud_order_by as $key_sub_menu_crud): ?>
										<a href="<?= $key_sub_menu_crud['lbl_az_menu_crud_t_url']; ?>read/" class="btn btn-sm btn-outline-dark">
											<em class="<?= $key_sub_menu_crud['lbl_az_icon_t_name']; ?>"></em>
											<span><?= $key_sub_menu_crud['lbl_az_menu_crud_t_name']; ?></span>
										</a>
									<?php endforeach; ?>
								</div>
							<?php endif; ?>
							<div class="card-box table-responsive">
								<div class="form-group">
									<?php if (false != $df_sql_permits_t_value_create): ?>
										<a href="<?= $df_var_controller; ?>create/" class="btn btn-sm btn-outline-success">
											<em class="mdi mdi-plus-circle-multiple-outline"></em>
											<span>Añadir Registro Nuevo</span>
										</a>
									<?php endif ?>
									<?php if (false != $df_sql_permits_t_value_read_eliminate): ?>
										<a href="<?= $df_var_controller; ?>eliminate/" class="btn btn-sm btn-outline-danger">
											<em class="mdi mdi-delete-forever"></em>
											<span>Registros Eliminados</span>
										</a>
									<?php endif ?>
								</div>
								<table id="datatable-buttons" class="table table-sm table-condensed table-striped table-bordered">
									<thead>
										<tr>
											<th width="1%">#</th>
											<th>Nombre</th>
											<th>Categoria</th>
											<th>Creado Por</th>
											<th>Acciones</th>
										</tr>
									</thead>
									<tbody>
										<?php if (false != $df_sql_controller_read): ?>
											<?php foreach ($df_sql_controller_read as $key): ?>
												<tr>
													<td width="1%">#</td>
													<td><?= $key['lbl_pd_brand_t_name']; ?></td>
													<td><?= $key['lbl_pd_category_brand_t_name'] ?></td>
													<td><?= $key['lbl_az_user_t_login_created']; ?></td>
													<td width="13%">
														<?php if (false != $df_sql_permits_t_value_update): ?>
															<a href="<?= $df_var_controller; ?>update/<?= $key['lbl_pd_brand_id_pd_brand']; ?>/" class="btn btn-sm btn-outline-dark">
																<em class="mdi mdi-pen"></em>
															</a>
														<?php endif ?>
														<?php if (false != $df_sql_permits_t_value_change): ?>
															<a href="<?= $df_var_controller; ?>change/<?= $key['lbl_pd_brand_id_pd_brand']; ?>/" class="btn btn-sm btn-outline-dark">
																<em class="mdi mdi-autorenew"></em>
															</a>
														<?php endif ?>
														<?php if (false != $df_sql_permits_t_value_detail): ?>
															<a href="<?= $df_var_controller; ?>detail/<?= $key['lbl_pd_brand_id_pd_brand']; ?>/" class="btn btn-sm btn-outline-dark">
																<em class="mdi mdi-format-list-numbers"></em>
															</a>
														<?php endif ?>
														<?php if (false != $df_sql_permits_t_value_remove): ?>
															<!--<button class="form_modal_delete_temp_pd_brand btn btn-sm btn-outline-danger" data-toggle="modal" id="<?= $key['lbl_pd_brand_id_pd_brand']; ?>">
																<em class="mdi mdi-delete-forever"></em>
															</button>-->
															<!--<a href="#" class="_ini_remove_modal_pd_brand btn btn-sm btn-outline-danger" id="<?= $key['lbl_pd_brand_id_pd_brand']; ?>">
																<em class="mdi mdi-delete-forever"></em>
															</a>-->
															<button type="button" class="_ini_remove_modal_pd_brand btn btn-sm btn-outline-danger" id="<?= $key['lbl_pd_brand_id_pd_brand']; ?>">
																<em class="mdi mdi-delete-forever"></em>
															</button>
														<?php endif ?>
													</td>
												</tr>

												<div class="modal fade bs-example-modal-sm" id="myModalRemove<?= $key['lbl_pd_brand_id_pd_brand']; ?>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="display: none;" data-keyboard="false" data-backdrop="static">
													<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_create_pd_daily_activities">
														<div class="modal-dialog modal-sm">
															<div class="modal-content">
																<div class="modal-header">
																	<h6 class="text-inverse" id="mySmallModalLabel">Eliminar Registro</h6>
																</div>
																<div class="modal-body">
																	Puedes editarla si solo necesitas cambiar algo.
																	<input type="text" name="field_id" id="field_id" value="<?= $key['lbl_pd_brand_id_pd_brand']; ?>">
																	<span><?= $key['lbl_pd_brand_id_pd_brand']; ?></span>
																</div>
																<div class="modal-footer">
																	<button type="button" class="btn btn-sm btn-outline-dark" data-dismiss="modal">
																		<em class="mdi mdi-content-save-all"></em>
																		<span>Cancelar</span>
																	</button>
																	<?php if (false != $df_sql_permits_t_value_update): ?>
																		<a href="<?= $df_var_controller; ?>update/<?= $key['lbl_pd_brand_id_pd_brand']; ?>/" class="btn btn-sm btn-outline-dark">
																			<em class="mdi mdi-pen"></em>
																			<span>Editar</span>
																		</a>
																	<?php endif ?>
																	<?php if (false != $df_sql_permits_t_value_remove): ?>
																		<button type="button" class="btn btn-sm btn-outline-danger" id="form_btn_remove_pd_daily_activities">
																			<em class="mdi mdi-delete-forever"></em>
																			<span>Remover</span>
																		</button>
																	<?php endif ?>
																	<!--<a href="<?= $df_var_controller; ?>remove/<?= $key['lbl_pd_brand_id_pd_brand']; ?>/" class="btn btn-sm btn-outline-danger">
																		<em class="mdi mdi-delete-forever"></em>
																		<span>Eliminar Registro</span>
																	</a>-->
																</div>
															</div>
														</div>
													</form>
												</div>
											<?php endforeach; ?>
										<?php endif; ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?= $this->insert('backend/design/footer'); ?>
		</div>
	</div>

	<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_delete_az_b">
		<div id="myModalDeleteTemp" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;" data-keyboard="false" data-backdrop="static">
			<div class="modal-dialog modal-lg" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="myLargeModalLabel">
							<span>Confirmar Eliminacion</span>
						</h5>
					</div>
					<div class="modal-body">
						<!--<div class="alert hide" id="form_ajax_az_b"></div>-->
						<div class="form-group hide-p" id="form_ocult_delete">
							<label>
								<span>Id:</span>
							</label>
							<div class="input-group input-group-sm">
								<input type="text" name="field_id" id="field_id" class="form-control" placeholder="Digita el texto ..." required="" readonly="true" disabled="true" onpaste="return true;" value="<?= $key['lbl_pd_brand_id_pd_brand']; ?>">
							</div>
						</div>
						<div class="alert alert-info">
							¿Estas seguro de eliminar el registro temporal de la base de datos?
						</div>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-sm btn-outline-dark" data-dismiss="modal">
							<em class="mdi mdi-call-missed"></em>
							<span>Cancelar</span>
						</button>
						<button type="button" class="btn btn-sm btn-outline-danger" id="btn_delete_az_b">
							<em class="mdi mdi-delete-forever"></em>
							<span>Eliminar</span>
						</button>
					</div>
				</div>
			</div>
		</div>
	</form>
	<?= $this->insert('backend/design/script'); ?>
</body>
</html>