<?= $this->insert('backend/design/header'); ?>
<body class="fixed-left">
	<div id="wrapper">
		<?= $this->insert('backend/design/topbar'); ?>
		<?= $this->insert('backend/design/sidebar-start'); ?>
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<?= $this->insert('backend/design/content-menu'); ?>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="card-box table-responsive">
								<div class="form-group">
									<?php if (false != $df_sql_permits_t_value_read_all): ?>
										<a href="<?= $df_var_controller; ?>read/" class="btn btn-sm btn-outline-dark">
											<em class="mdi mdi-arrow-left-bold-hexagon-outline"></em>
											<span>Listar Resultados</span>
										</a>
									<?php endif ?>
								</div>
								<table id="datatable-buttons" class="table table-sm table-condensed table-striped table-bordered">
									<thead>
										<tr>
											<th width="1%">#</th>
											<th>Nombre</th>
											<th>Campaña</th>
											<th>Tipo Definicion</th>
											<th>Tipo Gestion</th>
											<th>Creado Por</th>
											<th>Acciones</th>
										</tr>
									</thead>
									<tbody>
										<?php if (false != $df_sql_controller_eliminate): ?>
											<?php foreach ($df_sql_controller_eliminate as $key): ?>
												<tr>
													<td width="1%">#</td>
													<td><?= $key['lbl_pd_management_tree_t_name']; ?></td>
													<td><?= $key['lbl_pd_campaign_t_name']; ?></td>
													<td><?= $key['lbl_pd_type_definition_t_name']; ?></td>
													<td><?= $key['lbl_pd_type_management_t_name']; ?></td>
													<td><?= $key['lbl_az_user_t_login_created']; ?></td>
													<?php if (false != $df_sql_permits_t_value_delete): ?>
														<td>
															<a href="<?= $df_var_controller; ?>delete/<?= $key['lbl_pd_management_tree_id_pd_management_tree']; ?>/" class="btn btn-sm btn-outline-danger">
																<em class="mdi mdi-delete-forever"></em>
															</a>
														</td>
													<?php endif ?>
												</tr>
											<?php endforeach; ?>
										<?php endif; ?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?= $this->insert('backend/design/footer'); ?>
		</div>
	</div>
	<?= $this->insert('backend/design/script'); ?>
</body>
</html>