INSERT INTO `bd_az_development`.`az_neighborhood` (`m_by_created`, `m_by_modified`, `m_date_created`, `m_date_modified`, `m_deleted`, `m_description`, `m_level`, `m_status`, `t_name`) VALUES
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Canaima'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'La Floresta De La Sabana'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Torca'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Alto De Serrezuela'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Balcones De Vista Hermosa'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Balmoral Norte'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Buenavista'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Chaparral'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'El Codito'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'El Refugio De San Antonio'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'El Verbenal'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Horizontes'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'La Estrellita'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'La Frontera'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'La Llanurita'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Los Consuelos'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Maranta'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Maturin'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Medellin'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Mirador Del Norte'),
('0', '0', NOW(), NOW(), '0', '', '1', '0', 'Nuevo Horizonte');