						<div class="row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<div class="page-title-box">
									<h4 class="page-title">
										<span>Dashboard</span>
									</h4>
									<ol class="breadcrumb float-right">
										<li class="breadcrumb-item">
											<a href="home/">
												<span><?= APP ?></span>
											</a>
										</li>
										<li class="breadcrumb-item active">
											<span>Dashboard</span>
										</li>
									</ol>
									<div class="clearfix"></div>
								</div>
							</div>
						</div>
