CREATE TABLE `bd_az_framework`.`pd_exchange_data_personal` (
	`id_pd_exchange_data_personal` bigint(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Id',
	`m_by_created` bigint(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Creado Por',
	`m_by_modified` bigint(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Modificado Por',
	`m_date_created` datetime COLLATE utf8_unicode_ci NOT NULL COMMENT 'Fecha Creado',
	`m_date_modified` datetime COLLATE utf8_unicode_ci NOT NULL COMMENT 'Fecha Modificado',
	`m_deleted` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Eliminado',
	`m_description` longtext COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Descripcion',
	`m_level` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nivel',
	`m_status` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado',
	`m_temp` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Temporal',
	`t_address` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Direcccion',
	`t_birth_date` date COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Fecha Nacimiento',
	`t_email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Correo Electronico',
	`t_identification` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Identificacion',
	`t_names` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombres',
	`t_phone_fixed` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Telefono Fijo',
	`t_phone_movil` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Telefono Movil',
	`t_surnames` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Apellidos',
	`u_pd_birth_place_t_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre',
	`u_pd_civil_status_t_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre',
	`u_pd_document_type_t_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre',
	`u_pd_eps_t_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre',
	`u_pd_level_study_t_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre',
	`u_pd_neighborhood_t_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre',
	`u_pd_pension_t_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Nombre',
	`v_id_pd_data_personal` bigint(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Id'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `bd_az_framework`.`pd_exchange_data_personal`
	ADD PRIMARY KEY (`id_pd_exchange_data_personal`),
	ADD KEY `IDX_id_pd_exchange_data_personal` (`id_pd_exchange_data_personal`),
	ADD KEY `IDX_m_by_created` (`m_by_created`),
	ADD KEY `IDX_m_by_modified` (`m_by_modified`),
	ADD KEY `IDX_m_date_created` (`m_date_created`),
	ADD KEY `IDX_m_date_modified` (`m_date_modified`),
	ADD KEY `IDX_m_deleted` (`m_deleted`),
	ADD KEY `IDX_m_level` (`m_level`),
	ADD KEY `IDX_m_status` (`m_status`),
	ADD KEY `IDX_m_temp` (`m_temp`),
	ADD KEY `IDX_t_address` (`t_address`),
	ADD KEY `IDX_t_birth_date` (`t_birth_date`),
	ADD KEY `IDX_t_email` (`t_email`),
	ADD KEY `IDX_t_identification` (`t_identification`),
	ADD KEY `IDX_t_names` (`t_names`),
	ADD KEY `IDX_t_phone_fixed` (`t_phone_fixed`),
	ADD KEY `IDX_t_phone_movil` (`t_phone_movil`),
	ADD KEY `IDX_t_surnames` (`t_surnames`),
	ADD KEY `IDX_u_pd_birth_place_t_name` (`u_pd_birth_place_t_name`),
	ADD KEY `IDX_u_pd_civil_status_t_name` (`u_pd_civil_status_t_name`),
	ADD KEY `IDX_u_pd_document_type_t_name` (`u_pd_document_type_t_name`),
	ADD KEY `IDX_u_pd_eps_t_name` (`u_pd_eps_t_name`),
	ADD KEY `IDX_u_pd_level_study_t_name` (`u_pd_level_study_t_name`),
	ADD KEY `IDX_u_pd_neighborhood_t_name` (`u_pd_neighborhood_t_name`),
	ADD KEY `IDX_u_pd_pension_t_name` (`u_pd_pension_t_name`),
	ADD KEY `IDX_v_id_pd_data_personal` (`v_id_pd_data_personal`);

ALTER TABLE `bd_az_framework`.`pd_exchange_data_personal`
	MODIFY `id_pd_exchange_data_personal` bigint(255) NOT NULL AUTO_INCREMENT;