CREATE TABLE `bd_az_framework`.`pd_paysheet` (
	`id_pd_paysheet` bigint(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Id',
	`m_by_created` bigint(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Creado Por',
	`m_by_modified` bigint(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Modificado Por',
	`m_date_created` datetime COLLATE utf8_unicode_ci NOT NULL COMMENT 'Fecha Creado',
	`m_date_modified` datetime COLLATE utf8_unicode_ci NOT NULL COMMENT 'Fecha Modificado',
	`m_deleted` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Eliminado',
	`m_description` longtext COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Descripcion',
	`m_level` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Nivel',
	`m_status` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Estado',
	`m_temp` tinyint(1) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Temporal',
	`t_base_salary` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Salario Base',
	`t_bonuses` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Bonos',
	`t_contribution_to_benefit` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Aporte Beneficiar',
	`t_employer_health` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Salud Empleador',
	`t_employer_pension` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Pension Empleador',
	`t_health_employee` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Salud Empleado',
	`t_holidays` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Vacaciones',
	`t_loan` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Prestamo',
	`t_monthly_salary` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Salario Mensual',
	`t_net_to_pay` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Neto A Pagar',
	`t_pension_employee` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Pension Empleado',
	`t_retefuent` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Retefuente',
	`t_total_accrued` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Total Devengado',
	`t_total_deductions` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Total Deducciones',
	`t_transport_assistance` decimal(26,0) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Auxilio Transporte',
	`v_id_pd_data_personal` bigint(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Id',
	`v_id_pd_worked_period` bigint(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Id'

) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `bd_az_framework`.`pd_paysheet`
	ADD PRIMARY KEY (`id_pd_paysheet`),
	ADD KEY `IDX_id_pd_paysheet` (`id_pd_paysheet`),
	ADD KEY `IDX_m_by_created` (`m_by_created`),
	ADD KEY `IDX_m_by_modified` (`m_by_modified`),
	ADD KEY `IDX_m_date_created` (`m_date_created`),
	ADD KEY `IDX_m_date_modified` (`m_date_modified`),
	ADD KEY `IDX_m_deleted` (`m_deleted`),
	ADD KEY `IDX_m_level` (`m_level`),
	ADD KEY `IDX_m_status` (`m_status`),
	ADD KEY `IDX_m_temp` (`m_temp`),
	ADD KEY `IDX_t_base_salary` (`t_base_salary`),
	ADD KEY `IDX_t_bonuses` (`t_bonuses`),
	ADD KEY `IDX_t_contribution_to_benefit` (`t_contribution_to_benefit`),
	ADD KEY `IDX_t_employer_health` (`t_employer_health`),
	ADD KEY `IDX_t_employer_pension` (`t_employer_pension`),
	ADD KEY `IDX_t_health_employee` (`t_health_employee`),
	ADD KEY `IDX_t_holidays` (`t_holidays`),
	ADD KEY `IDX_t_loan` (`t_loan`),
	ADD KEY `IDX_t_monthly_salary` (`t_monthly_salary`),
	ADD KEY `IDX_t_net_to_pay` (`t_net_to_pay`),
	ADD KEY `IDX_t_pension_employee` (`t_pension_employee`),
	ADD KEY `IDX_t_retefuent` (`t_retefuent`),
	ADD KEY `IDX_t_total_accrued` (`t_total_accrued`),
	ADD KEY `IDX_t_total_deductions` (`t_total_deductions`),
	ADD KEY `IDX_t_transport_assistance` (`t_transport_assistance`),
	ADD KEY `IDX_v_id_pd_data_personal` (`v_id_pd_data_personal`),
	ADD KEY `IDX_v_id_pd_worked_period` (`v_id_pd_worked_period`);

ALTER TABLE `bd_az_framework`.`pd_paysheet`
	MODIFY `id_pd_paysheet` bigint(255) NOT NULL AUTO_INCREMENT;