<?= $this->insert('frontend/design/header'); ?>
<?= $this->insert('frontend/design/body'); ?>
	<?= $this->insert('frontend/design/tagline'); ?>
	<?= $this->insert('frontend/design/navbar'); ?>
	<?= $this->insert('frontend/design/parallax'); ?>

	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<h1 class="text-center">
						<i class="ti-face-sad text-danger"></i>
						<span>Oops!</span> - <span class="text-success">Error 404</span>
					</h1>
					<h4 class="text-center">
						Esta pagina no se pudo encontrar o no se encuentra disponible.
					</h4>
					<h4 class="text-center">
						Parece que la pagina que esta buscando no existe. Lamentamos la incindencia.
					</h4>
				</div>
			</div>
		</div>
	</section>

	<?= $this->insert('frontend/design/footer'); ?>
	<?= $this->insert('frontend/design/script'); ?>
</body>
</html>