<?= $this->insert('frontend/design/header'); ?>
<?= $this->insert('frontend/design/body'); ?>
	<?= $this->insert('frontend/design/tagline'); ?>
	<?= $this->insert('frontend/design/navbar'); ?>
	<?= $this->insert('frontend/design/parallax'); ?>
	<section class="section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-xs-12 col-sm-12 col-md-7 col-lg-8">
					<div class="text-center">
						<h1 class="header-title zoomIn animated wow" data-wow-delay=".1s">
							Nosotros
						</h1>
						<p class="text-custom zoomIn animated wow" data-wow-delay=".2s">
							Prisma Direct es una empresa Colombiana reconocida por su compromiso con el cliente.
						</p>
					</div>
					<div class="text-center">
						<div class="zoomIn animated fadeInLeft wow" data-wow-delay=".1s">
							<p class="text-custom">
								Ofrece su experiencia y calidad, llevando con éxito cada proyecto. contamos con personal capacitado y calificado en todos los productos y servicios que comercializamos.
							</p>
							<p class="text-custom">
								Nuestros productos y servicios permiten solucionar las necesidades de los clientes sin grandes inversiones en tecnología, en capacitación, en recursos humanos y lo más importante, sin que el cliente se desenfoque de su negocio.
							</p>
							<p class="text-custom">
								Prisma Direct es una empresa que escucha, vé y propone la mejor solución, buscando la estrategia más rentable para el crecimiento del negocio de sus clientes.
							</p>
							<p class="text-custom">
								Podemos actuar como su agencia de cobro. Nuestra organización cuenta con tecnología y respaldo humano que permite ofrecer servicios de Cobranza, Outsourcing y Solidario:
							</p>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
					<div class="card m-b-20 zoomIn animated">
						<div class="card-body">
							<h5 class="card-title text-center">
								El Personaje Calidoso
							</h5>
						</div>
						<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner" role="listbox">
								<div class="carousel-item active">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_advanced_solutions.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_cobranzas.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_electronics.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_franquicia.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_mobile.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_outsorcing.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_renting.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_services.jpg" />
								</div>
								<div class="carousel-item">
									<img class="thumb-img d-block img-fluid" src="views/frontend/images/img_prisma_training.jpg" />
								</div>
							</div>
							<a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
								<span class="carousel-control-prev-icon text-muted" aria-hidden="true"></span>
								<span class="sr-only">Previous</span>
							</a>
							<a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
								<span class="carousel-control-next-icon text-muted" aria-hidden="true"></span>
								<span class="sr-only">Next</span>
							</a>
						</div>
						<div class="card-body">
							<p class="card-text text-center">
								Conozca a <span class="text-danger">Calidoso</span> la mascota de Prisma Direct en todas sus presentaciones para cada unidad de servicio
							</p>
						</div>
					</div>
					
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="prisma_cobranzas">
					<div class="service-detail">
						<div class="service-item animated fadeInLeft wow" data-wow-delay=".1s">
							<i class=" ti-bookmark-alt"></i>
						</div>
						<div class="service-detail">
							<h4 class="m-t-0 header-title">
								Prisma Cobranzas
							</h4>
							<ul class="list-unstyled">
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Agente Virtual (SMS, e-mail-audios).
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera preventiva.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera administrativa.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera pre jurídica.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera castigada.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro Jurídico
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Visitas Domiciliarias.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Sofware para cobro de cartera.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Actualización bases datos
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobranza efectiva
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="prisma_outsourcing">
					<div class="service-detail">
						<div class="service-item animated fadeInLeft wow" data-wow-delay=".1s">
							<i class=" ti-bookmark-alt"></i>
						</div>
						<div class="service-detail">
							<h4 class="m-t-0 header-title">
								Prisma Outsourcing
							</h4>
							<ul class="list-unstyled">
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Tele mercadeo de Productos.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Campañas de entrada y salida de llamadas.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Encuestas.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Agente Virtual (SMS, e-mail-audios).
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Visitas Domiciliarias.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Software.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Verificación de información comercial (área crédito)
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Actualización bases datos
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="prisma_solidario">
					<div class="service-detail">
						<div class="service-item animated fadeInLeft wow" data-wow-delay=".1s">
							<i class=" ti-bookmark-alt"></i>
						</div>
						<div class="service-detail">
							<h4 class="m-t-0 header-title">
								Prisma Solidario
							</h4>
							<ul class="list-unstyled">
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Tele mercadeo de Productos.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Campañas de entrada y salida de llamadas.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Encuestas.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Agente Virtual (SMS, e-mail-audios).
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera preventiva.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera administrativa.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera pre jurídica.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro de cartera castigada.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro Jurídico
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobro Jurídico
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Visitas Domiciliarias.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Sofware para cobro de cartera.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Verificación de información comercial (área crédito).
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Actualización bases datos.
								</li>
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									Cobranza efectiva
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" id="prisma_software">
					<div class="service-detail">
						<div class="service-item animated fadeInLeft wow" data-wow-delay=".1s">
							<i class=" ti-bookmark-alt"></i>
						</div>
						<div class="service-detail">
							<h4 class="m-t-0 header-title">
								Prisma Software
							</h4>
							<ul class="list-unstyled">
								<li class="text-custom">
									<i class="text-danger ti-arrow-circle-right"></i>
									PCB ® Software de Cobranza.
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--<section class="section bg-gray" id="history">
		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<div class="feature-detail">
						<h2 class="title fadeIn animated wow" data-wow-delay=".1s">
							Clean and Ultra Modern Design
						</h2>
						<p class="sub fadeIn animated wow" data-wow-delay=".2s">
							Constituto voluptatibus mei ex. Eum soleat lorem Ipsum is simply dummy <br/> text of the printing and typesetting industry.
						</p>
						<ul class="list-unstyled">
							<li>
								<i class=" ti-arrow-circle-right"></i>
								Aliquam a augue suscipit, bibendum luctus neque. Vestibulum laoreet rhoncus ipsum, bibendum ullamcorper hendrerit tellus.
							</li>
							<li>
								<i class=" ti-arrow-circle-right"></i>
								We put a lot of effort in design, as it’s the most important ingredient of successful website.
							</li>
						</ul>
						<a href="" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow" data-wow-delay=".4s">
							Buy Now
						</a>
					</div>
				</div>
				<div class="col-sm-6">
					<img src="views/frontend/images/mac.png" class="img-fluid">
				</div>
			</div>
		</div>
	</section>-->
	<!--<section class="section" id="features1">
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					<img src="views/frontend/images/tab2.png" class="img-fluid screen-space">
				</div>
				<div class="col-md-6 ml-auto">
					<div class="feature-detail">
						<h2 class="title fadeIn animated wow" data-wow-delay=".1s">
							Clean and Ultra Modern Design
						</h2>
						<p class="sub fadeIn animated wow" data-wow-delay=".2s">
							Constituto voluptatibus mei ex. Eum soleat lorem Ipsum is simply dummy <br/> text of the printing and typesetting industry.
						</p>
						<ul class="list-unstyled">
							<li>
								<i class=" ti-arrow-circle-right"></i>
								Aliquam a augue suscipit, bibendum luctus neque. Vestibulum laoreet rhoncus ipsum, bibendum ullamcorper hendrerit tellus.
							</li>
							<li>
								<i class=" ti-arrow-circle-right"></i>
								We put a lot of effort in design, as it’s the most important ingredient of successful website.
							</li>
						</ul>
						<a href="" class="btn btn-primary btn-rounded w-lg animated fadeInDown wow" data-wow-delay=".4s">
							Buy Now
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>-->
	<!--<section class="fun-facts bg-img-2 parallax" data-stellar-background-ratio="0.5">
		<div class="bg-overlay"></div>
		<div class="container">
			<div class="row text-center">
				<div class="col-md-3 col-sm-3 facts">
					<i class="ti-pencil-alt"></i>
						<h1>
							<span class="counter">6577</span> k
						</h1>
					<h4>
						Lines Coded
					</h4>
				</div>
				<div class="col-md-3 col-sm-3 facts">
					<i class="ti-timer"></i>
					<h1>
						<span class="counter">7800</span> +
					</h1>
					<h4>
						Working Hours
					</h4>
				</div>
				<div class="col-md-3 col-sm-3 facts">
					<i class="ti-briefcase"></i>
					<h1 class="counter">
						399
					</h1>
					<h4>
						No. Of Template
					</h4>
				</div>
				<div class="col-md-3 col-sm-3 facts">
					<i class=" ti-user"></i>
					<h1 class="counter">
						9995
					</h1>
					<h4>
						Clients
					</h4>
				</div>
			</div>
		</div>
	</section>-->
	<!--<section class="section" id="pricing">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center">
					<h1 class="title zoomIn animated wow" data-wow-delay=".1s">
						Simple Pricing
					</h1>
					<p class="sub-title zoomIn animated wow" data-wow-delay=".2s">
						Constituto voluptatibus mei ex. Eum soleat lorem Ipsum is simply dummy <br/> text of the printing and typesetting industry.
					</p>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-lg-10">
					<div class="row">
						<div class="col-md-4">
							<div class="pricing-item animated fadeInLeft wow" data-wow-delay=".3s">
								<div class="pricing-item-inner">
									<div class="pricing-wrap">
										<div class="pricing-num pricing-num-pink">
											<sup>$</sup>99
										</div>
										<div class="pr-per">
											per month
										</div>
										<div class="pricing-title">
											Starter Pack
										</div>
										<div class="pricing-features">
											<ul class="sf-list pr-list">
												<li>
													5 Projects
												</li>
												<li>
													1 GB Storage
												</li>
												<li>
													No Domain
												</li>
												<li>
													1 User
												</li>
												<li>
													Free Support
												</li>
											</ul>
										</div>
										<div class="pr-button">
											<a href="" class="btn btn-primary btn-rnd">
												Buy Now
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="pricing-item main animated fadeInLeft wow" data-wow-delay=".5s">
								<div class="ribbon">
									<span>POPULAR</span>
								</div>
								<div class="pricing-item-inner">
									<div class="pricing-wrap">
										<div class="pricing-num">
											<sup>$</sup>199
										</div>
										<div class="pr-per">
											per month
										</div>
										<div class="pricing-title">
											Professional Pack
										</div>
										<div class="pricing-features">
											<ul class="sf-list pr-list">
												<li>
													5 Projects
												</li>
												<li>
													1 GB Storage
												</li>
												<li>
													No Domain
												</li>
												<li>
													1 User
												</li>
												<li>
													Free Support
												</li>
											</ul>
										</div>
										<div class="pr-button">
											<a href="" class="btn btn-primary btn-rnd">
												Buy Now
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<div class="pricing-item animated fadeInLeft wow" data-wow-delay=".7s">
								<div class="pricing-item-inner">
									<div class="pricing-wrap">
										<div class="pricing-num pricing-num-yellow">
											<sup>$</sup>299
										</div>
										<div class="pr-per">
											per month
										</div>
										<div class="pricing-title">
											Enterprise Pack
										</div>
										<div class="pricing-features">
											<ul class="sf-list pr-list">
												<li>
													5 Projects
												</li>
												<li>
													1 GB Storage
												</li>
												<li>
													No Domain
												</li>
												<li>
													1 User
												</li>
												<li>
													Free Support
												</li>
											</ul>
										</div>
										<div class="pr-button">
											<a href="" class="btn btn-primary btn-rnd">
												Buy Now
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>-->
	<!--<section class="section bg-gray" id="faq">
		<div class="container">
			<div class="row">
				<div class="col-sm-12 text-center">
					<h1 class="title zoomIn animated wow" data-wow-delay=".1s">
						FAQ
					</h1>
					<p class="sub-title zoomIn animated wow" data-wow-delay=".2s">
						Constituto voluptatibus mei ex. Eum soleat lorem Ipsum is simply dummy <br/> text of the printing and typesetting industry.
					</p>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-5">
					<div class="animated fadeInLeft wow" data-wow-delay=".1s">
						<h4 class="question" data-wow-delay=".1s">
							What is Lorem Ipsum?
						</h4>
						<p class="answer">
							Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
						</p>
					</div>
					<div class="animated fadeInLeft wow" data-wow-delay=".3s">
						<h4 class="question">
							Why use Lorem Ipsum?
						</h4>
						<p class="answer m-b-0">
							Lorem ipsum dolor sit amet, in mea nonumes dissentias dissentiunt, pro te solet oratio iriure. Cu sit consetetur moderatius intellegam, ius decore accusamus te. Ne primis suavitate disputando nam. Mutat convenirete.
						</p>
					</div>
				</div>
				<div class="col-md-5">
					<div class="animated fadeInRight wow" data-wow-delay=".2s">
						<h4 class="question">
							Is safe use Lorem Ipsum?
						</h4>
						<p class="answer">
							Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
						</p>
					</div>
					<div class="animated fadeInRight wow" data-wow-delay=".4s">
						<h4 class="question">
							When can be used?
						</h4>
						<p class="answer m-b-0">
							Lorem ipsum dolor sit amet, in mea nonumes dissentias dissentiunt, pro te solet oratio iriure. Cu sit consetetur moderatius intellegam, ius decore accusamus te. Ne primis suavitate disputando nam. Mutat convenirete.
						</p>
					</div>
				</div>
			</div>
		</div>
	</section>-->	
	<?= $this->insert('frontend/design/footer'); ?>
	<?= $this->insert('frontend/design/script'); ?>
</body>
</html>