<?= $this->insert('frontend/design/header'); ?>
<?= $this->insert('frontend/design/body'); ?>
	<?= $this->insert('frontend/design/tagline'); ?>
	<?= $this->insert('frontend/design/navbar'); ?>

	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="login_form">
						<div class="alert hide" id="ajax_login"></div>
						<div class="form-group row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<label>
									<span>Usuario:</span>
								</label>
								<div class="input-group">
									<span class="input-group-addon">
										<i class="ti-user"></i>
									</span>
									<input type="text" name="field_login" class="form-control" placeholder="Usuario" required="" />
								</div>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<label>
									<span>Contraseña:</span>
								</label>
								<div class="input-group">
									<span class="input-group-addon">
										<i class="ti-key"></i>
									</span>
									<input type="password" name="fiel_password" class="form-control" placeholder="Contraseña" required="" />
								</div>
							</div>
						</div>
						<div class="form-group text-right m-t-20">
							<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<button type="button" id="login" class="btn btn-primary btn-custom w-md waves-effect waves-light">
									<span>Inciar Sesion</span>
								</button>
							</div>
						</div>
						<!--<div class="form-group row m-t-30">
							<div class="col-xs-12 col-sm-7 col-md-7 col-lg-10">
								<a href="recovery" class="text-muted">
									<i class="ti-lock m-r-5"></i>
									<span>¿Olvidaste tu contraseña?</span>
								</a>
							</div>
							<div class="col-xs-12 col-sm-5 col-md-5 col-lg-2">
								<a href="register" class="text-muted">
									<span>Crear una cuenta</span>
								</a>
							</div>
						</div>-->
					</form>
				</div>
			</div>
		</div>
	</section>

	<?= $this->insert('frontend/design/footer'); ?>
	<?= $this->insert('frontend/design/script'); ?>
</body>
</html>