<?= $this->insert('frontend/design/header'); ?>
<?= $this->insert('frontend/design/body'); ?>
	<?= $this->insert('frontend/design/tagline'); ?>
	<?= $this->insert('frontend/design/navbar'); ?>
	<?= $this->insert('frontend/design/parallax'); ?>

	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					Controlador Recuperar Contraseña
				</div>
			</div>
		</div>
	</section>

	<?= $this->insert('frontend/design/footer'); ?>
	<?= $this->insert('frontend/design/script'); ?>
</body>
</html>