<?= $this->insert('frontend/design/header'); ?>
<?= $this->insert('frontend/design/body'); ?>
	<?= $this->insert('frontend/design/tagline'); ?>
	<?= $this->insert('frontend/design/navbar'); ?>
	<?= $this->insert('frontend/design/parallax'); ?>

	<section class="section">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
					<h1 class="text-center">
						<i class="ti-face-sad text-danger"></i>
						<span>Oops!</span> - <span class="text-success">Advertencia</span>
					</h1>
					<h4 class="text-center">
						Esta pagina no se pudo encontrar debido a que el resultado cargado no existe.
					</h4>
					<h4 class="text-center">
						¿Continua apareciendo el error? Cierra y vuelve a cargar el registro para cargar la informacion correspondiente.
					</h4>
					<h4 class="text-center">
						En caso de no funcionar, contactacte con el administrador de la pagina web.
					</h4>
				</div>
			</div>
		</div>
	</section>

	<?= $this->insert('frontend/design/footer'); ?>
	<?= $this->insert('frontend/design/script'); ?>
</body>
</html>