<?= $this->insert('backend/design/header'); ?>
<body class="fixed-left">
	<div id="wrapper">
		<?= $this->insert('backend/design/topbar'); ?>
		<?= $this->insert('backend/design/sidebar-start'); ?>
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<?= $this->insert('backend/design/content-menu'); ?>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<h1 class="text-center">
								<i class="ti-face-sad text-danger"></i>
								<span>Oops!</span> - <span class="text-success">Acceso Prohibido</span>
							</h1>
							<h4 class="text-center">
								Esta pagina no tiene el acceso autorizado por parte de su usuario.
							</h4>
							<h4 class="text-center">
								Parece que la pagina a la que estas ingresando no se encuentra autorizada.
							</h4>
						</div>
					</div>
				</div>
			</div>
			<?= $this->insert('backend/design/footer'); ?>
		</div>
	</div>
	<?= $this->insert('backend/design/script'); ?>
</body>
</html>