<?= $this->insert('backend/design/header'); ?>
<body class="fixed-left">
	<div id="wrapper">
		<?= $this->insert('backend/design/topbar'); ?>
		<?= $this->insert('backend/design/sidebar-start'); ?>
		<?php $var_obj_session_menu_intern = new dvbmModel; ?>
		<?php $var_read_session_menu_intern = $var_obj_session_menu_intern->read_session_menu_intern(); ?>
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<?= $this->insert('backend/design/content-menu'); ?>
					<div class="row">
						<?php if (false != $var_read_session_menu_intern): ?>
							<?php foreach ($var_read_session_menu_intern as $key): ?>
								<div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
									<a href="<?= $key['lbl_az_me_t_url'] ?>">
										<div class="widget-bg-color-icon card-box fadeInDown animated">
											<div class="bg-icon bg-icon-primary pull-left">
												<i class="waves-effect <?= $key['lbl_az_i_t_name'] ?>"></i>
											</div>
											<div class="text-right">
												<!--<h3 class="text-dark m-t-10">
													<b class="counter">9,654</b>
												</h3>-->
												<p class="text-muted mb-0">
													<span><?= $key[az_i_i_m_r_t_name] ?></span>
												</p>
											</div>
											<div class="clearfix"></div>
										</div>
									</a>
								</div>
							<?php endforeach; ?>
						<?php endif; ?>
					</div>
				</div>
			</div>
			<?= $this->insert('backend/design/footer'); ?>
		</div>
	</div>
	<?= $this->insert('backend/design/script'); ?>
</body>
</html>