<?= $this->insert('backend/design/header'); ?>
<body class="fixed-left">
	<div id="wrapper">
		<?= $this->insert('backend/design/topbar'); ?>
		<?= $this->insert('backend/design/sidebar-start'); ?>
		<div class="content-page">
			<div class="content">
				<div class="container-fluid">
					<?= $this->insert('backend/design/content-menu'); ?>
					<div class="row">
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<div class="card-box table-responsive">
								<form class="form-horizontal" role="form" enctype="application/x-www-form-urlencoded" id="form_create_pd_paysheet">
									<div class="row">
										<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
											<div class="form-group">
												<a href="<?= $df_var_controller; ?>read/" class="btn btn-sm btn-outline-dark">
													<em class="mdi mdi-arrow-left-bold-hexagon-outline"></em>
													<span>Listar Resultados</span>
												</a>
												<button type="button" class="btn btn-sm btn-outline-success" id="form_btn_create_pd_paysheet">
													<em class="mdi mdi-content-save-all"></em>
													<span>Guardar Registro</span>
												</button>
											</div>
											<div class="hide" id="form_ajax_pd_paysheet"></div>
										</div>
										<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
											<div class="form-group">
												<label>
													<span>Identificacion:</span>
												</label>
												<div class="input-group input-group-sm">
													<select name="field_data_personal" id="field_data_personal" class="form-control" required="">
														<option value="0">Seleccionar</option>
														<option value="Completo">Completo</option>
														<?php if (false != $df_sql_select_tc_pd_data_personal): ?>
															<?php foreach ($df_sql_select_tc_pd_data_personal as $key): ?>
																<option value="<?= $key[d_pd_data_personal_id_pd_data_personal]; ?>">
																	<?= $key[d_pd_data_personal_t_identification] . ': ' . $key[d_pd_data_personal_t_names] . ' ' . $key[d_pd_data_personal_t_surnames]; ?>
																</option>
															<?php endforeach; ?>
														<?php else: ?>
															<option value="0">No existen resultados</option>
														<?php endif; ?>
													</select>
												</div>
											</div>
										</div>
										<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
											<div class="form-group">
												<label>
													<span>Periodo Trabajo:</span>
												</label>
												<div class="input-group input-group-sm">
													<select name="field_worked_period" id="field_worked_period" class="form-control" required="">
														<option value="0">Seleccionar</option>
														<option value="Completo">Completo</option>
														<?php if (false != $df_sql_select_tc_pd_worked_period): ?>
															<?php foreach ($df_sql_select_tc_pd_worked_period as $key): ?>
																<option value="<?= $key[d_pd_worked_period_id_pd_worked_period]; ?>">
																	<?= $key[d_pd_worked_period_t_name]; ?>
																</option>
															<?php endforeach; ?>
														<?php else: ?>
															<option value="0">No existen resultados</option>
														<?php endif; ?>
													</select>
												</div>
											</div>
										</div>
										<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
											<div class="card-box">
												<ul class="nav nav-tabs tabs-bordered">
													<li class="nav-item">
														<a href="#accrued" data-toggle="tab" aria-expanded="false" class="nav-link active">
															<span>Devengado</span>
														</a>
													</li>
													<li class="nav-item">
														<a href="#social_security" data-toggle="tab" aria-expanded="false" class="nav-link">
															<span>Seguridad Social</span>
														</a>
													</li>
													<li class="nav-item">
														<a href="#seduction" data-toggle="tab" aria-expanded="false" class="nav-link">
															<span>Deducciones</span>
														</a>
													</li>
												</ul>
												<div class="tab-content">
													<div class="tab-pane active" id="accrued">
														<div class="row">
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Salario Mensual:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_base_salary" id="field_base_salary" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_base_salary): ?>
																				<?php foreach ($df_sql_select_tc_pd_base_salary as $key): ?>
																					<option value="<?= $key[d_pd_base_salary_id_pd_base_salary]; ?>">
																						<?= number_format($key[d_pd_base_salary_t_value]); ?>
																					</option>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Salario Base:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_bonuses" id="field_bonuses" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_base_salary): ?>
																				<?php foreach ($df_sql_select_tc_pd_base_salary as $key): ?>
																					<option value="<?= $key[d_pd_base_salary_id_pd_base_salary]; ?>">
																						<?= number_format($key[d_pd_base_salary_t_value]); ?>
																					</option>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Auxilio Transporte:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<select name="field_contribution_to_benefit" id="field_contribution_to_benefit" class="form-control" required="">
																			<option value="0">Seleccionar</option>
																			<?php if (false != $df_sql_select_tc_pd_transport_assistance): ?>
																				<?php foreach ($df_sql_select_tc_pd_transport_assistance as $key): ?>
																					<option value="<?= $key[d_pd_transport_assistance_id_pd_transport_assistance]; ?>">
																						<?= number_format($key[d_pd_transport_assistance_t_value]); ?>
																					</option>
																				<?php endforeach; ?>
																			<?php else: ?>
																				<option value="0">No existen resultados</option>
																			<?php endif; ?>
																		</select>
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Vacaciones:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_employer_health" id="field_employer_health" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Bonos:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_employer_pension" id="field_employer_pension" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<!--<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Total Devengado:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_health_employee" id="field_health_employee" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>-->
														</div>
													</div>
													<div class="tab-pane" id="social_security">
														<div class="row">
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Pension Empleador:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_holidays" id="field_holidays" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Salud Empleador:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_loan" id="field_loan" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Salud Empleado:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_monthly_salary" id="field_monthly_salary" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Pension Empleado:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_net_to_pay" id="field_net_to_pay" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
														</div>
													</div>
													<div class="tab-pane" id="seduction">
														<div class="row">
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Prestamo:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_pension_employee" id="field_pension_employee" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Retefuente:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_retefuent" id="field_retefuent" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Aporte Beneficiar:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_total_accrued" id="field_total_accrued" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Total Deducciones:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_total_deductions" id="field_total_deductions" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
															<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
																<div class="form-group">
																	<label>
																		<span>Neto A Pagar:</span>
																	</label>
																	<div class="input-group input-group-sm">
																		<input type="text" name="field_transport_assistance" id="field_transport_assistance" class="form-control" placeholder="Digita el texto ..." required="">
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?= $this->insert('backend/design/footer'); ?>
		</div>
	</div>
	<?= $this->insert('backend/design/script'); ?>
</body>
</html>